### PR TITLE
Bug fix: sass call() deprecation warnings

### PR DESCRIPTION
**Pull request by alexthomas**

### CODE REVIEW

**Comment by mirisuzanne** [comment]
Hi @alexthomas - thanks for the patch!

There's just one issue. This fails on older versions of Sass, without `get-function` available. I think we'll need something like this:

```scss
// interpolate function name
$function: "#{$_type}-exists";

// if `get-function` exists, then we can use it
$function: if(function-exists(get-function), get-function($function), $function);

// call the function – either as a string, or as a first-class function
$_pass: call($function, $_i);
```

**Comment by mirisuzanne** [comment]
Are you willing to update the pull request so it works in all versions of Sass?

**Comment by alexthomas** [comment]
Hi Miriam,

I'll give it a red hot crack! (to coin an Ozzie phrase)

**Comment by mirisuzanne** [comment]
hmmm, this is a harder problem than I thought - because Susy will not actually have access to the referenced variables/functions/mixins once Sass 4.0 lands.

I guess we can punt until then?

**Comment by mirisuzanne** [comment]
Fixed by 8e5dab9259077d6c0

**Pull request closed without merging**
