### PR TITLE
fix segmentation fail for node-sass 3.4.2

### PR DESCRIPTION
**Pull request by inuscript**
I got "segmentation fault"  error with `node-sass@3.4.2`.
And try to avoid this error.

### CODE REVIEW

**Comment by ericam** [comment]
I've never seen this, but it looks like a bug in libsass. Have you reported it there? I can't recreate it in the [most current version](http://sassmeister.com/gist/66c3d77b46de41f6c85a). Sass allows you to iterate over any variable type, even if they are a single value. There's no reason to force it into a list before iterating. I have no issues with a temporary fix if this is a consistent bug for people in node-sass, but I want to make sure it's being handled at the source.

**Comment by inuscript** [comment]
Thank you for reply.
To be more accurate, I got this issue to call `@include container();`.

I generate issue sample. 
https://github.com/inuscript/sass-3-4-error

**Comment by inuscript** [comment]
I send this issue to libsass.
https://github.com/sass/libsass/issues/1752

**Comment by ericam** [comment]
Thanks!

**Comment by inuscript** [comment]
This issue may resolve soon and close this PR.
https://github.com/sass/libsass/pull/1756

And temporaly, I resolve this issue like

```sass
@include container(12): // pass some valie
```

**Pull request closed without merging**
