### PR TITLE
Update install.rst with gulp instructions

### PR DESCRIPTION
**Pull request by FNGR2911**
Hey everbody. I wrote a short description on how to use susy with gulp. Is this working for everybody?

### CODE REVIEW

**Comment by aaronagray** [comment]
Nice work! Thank you. Can you adjust the order of install instructions in a second commit? Here's the order @mirisuzanne and I have in mind:

```
Bundler or Rails
NPM and Webpack
Gulp
Grunt
Bower
Compass
```

**Comment by FNGR2911** [comment]
@aaronagray no problem, made a second commit. Hopefully it's the right order now :)

**Comment by mirisuzanne** [comment]
great! thanks!

**Comment by facelesspanda** [comment]
Noticed the changes were not reflected in [the oddbird site](http://susydocs.oddbird.net/en/latest/install/). Isn't this the most public docs?

**Comment by mirisuzanne** [comment]
@facelesspanda Thanks for noticing that. Looks like our readthedocs config is broken. @carljm I updated the repo (from `ericam/` to `oddbird/`) but it's still failing — can you look at it?

**Comment by carljm** [comment]
All the recent RTD builds passed, and it looks like the site does reflect this PR now. I'm not sure why it looks like there was a delay between the PR merge and the site update, but I can't find anything broken to fix.

**Comment by facelesspanda** [comment]
Indeed now the changes are reflected. Weird delay.

**Pull request merged**
